name: example
description: An example for arb_generator.
publish_to: 'none'
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons:
  intl:

dev_dependencies:
  flutter_lints: ^3.0.0
  arb_generator:
    path: ../

flutter:
  generate: true
  uses-material-design: true

arb_generator:
  input_filepath: "assets_dev/test.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2
