name: arb_generator
description: Generates ARB files from CSV files.
publish_to: 'none'
version: 0.0.1
homepage: https://github.com/defuncart/arb_generator
repository: https://github.com/defuncart/arb_generator
issue_tracker: https://github.com/defuncart/arb_generator/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  csv: ^5.0.0
  flappy_translator:
    git:
      url: https://github.com/smartnsoft/FlappyTranslator
      ref: 695e75e811112feb21e11b63ef3023e29e701079

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
